### ISSUE TITLE
Anonymity?

### ISSUE THREAD

**Issue by abonner1** [learn-co-curriculum/javascript-arrow-functions#8]
In working through the code under "ANONYMITY'S THE NAME OF THE GAME" when I create the the arrow function `anonymous` and ask for its name it says it named "anonymous". It doesn't give a blank ''.

**Comment by crwhitesides** [comment]
I just brought up the same [issue](https://github.com/learn-co-curriculum/javascript-arrow-functions/issues/9).

**Comment by danblondell** [comment]
I'm seeing the same thing in both Chrome and Safari's consoles.
